[target.'cfg(target_os = "macos")']
rustflags = [
  # let all Python Câ€‘API symbols remain undefined and be
  # looked up when the .dylib is loaded by Python
  "-C", "link-args=-undefined dynamic_lookup"
]