name: Update README ‚≠ê
on:
  schedule:
    - cron: "25 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1511815
          leaderboardId: 1511815
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2025
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README stars
